#!/bin/sh
rm -r cd
mkdir cd
cp isolinux.* cd
cp linux cd
cp initrd.gz cd
echo preseed.cfg | cpio -Hnewc -o --quiet |gzip -c >> cd/initrd.gz
mkisofs -o cd.iso -b isolinux.bin -c boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table cd
